### ISSUE TITLE
[Feature]: <Feature Name>Change language using google translator

### ISSUE THREAD

**Issue by yogeswari05** [Ajay-Dhangar/algo#1001]
### Feature Name

Change language using google translator

### Feature Description

I would be nice if we add a select language option.

### Motivation

Users may want to read the content in their native language.

### Feature Type

Other

### Does this feature require additional resources?

- [ ] Additional Documentation
- [ ] Third-Party Libraries
- [ ] UI/UX Design
- [ ] Other

**Comment by ajay-dhangar** [comment]
Thank you for your suggestion. I think it's a great idea to be able to change the language of the UI. I would suggest adding a drop-down menu that allows users to select their preferred language. The menu could include languages such as English, Hindi, and more. I have already implemented this feature on my site https://eco-farm-hub.github.io/goat-farming/hi/docs/. If you have any questions or need assistance, please ask.
