### ISSUE TITLE
[Bug]: <Brief description of the bug> footer resources element is not properly aligned in mobile screen. 

### ISSUE THREAD

**Issue by Suvadip-sana** [Ajay-Dhangar/algo#1013]
### Bug Summary

Resources element is not aligned properly in mobile screen. 

### Bug Description

As you seen on the screen shot. The resources element is not aligned properly like community element. 
It's not looks visually appealing. It should be in left side as the community element is. Then it's look good. 

### Steps to Reproduce

In mobile screen. See the footer. You clearly see this bug which I want to say. 

### Expected Behavior

It should be in left aligned. 

### Screenshots or Logs (Optional)

![Screenshot_2024-10-19-19-37-47-403_com android chrome](https://github.com/user-attachments/assets/1e979e1e-c49c-479a-b56a-4b49577a3933)

### Severity

Minor - cosmetic or minor issue

### Environment

- [X] Local Development
- [X] Staging
- [X] Production
- [X] Other

**Comment by ajay-dhangar** [comment]
I would like to get this issue resolved today. It is very important to me. If it is not resolved today, I will fix it myself. I can't wait for this any longer.

**Comment by Suvadip-sana** [comment]
@ajay-dhangar yes. Don't worry I made  PR today.
