### ISSUE TITLE
[Bug]: <Brief description of the bug> Alignment problem in footer for mobile screen

### ISSUE THREAD

**Issue by Suvadip-sana** [Ajay-Dhangar/algo#1027]
### Bug Summary

`Features, About Us, Contact, Privacy Policy`

### Bug Description

![image](https://github.com/user-attachments/assets/631e9746-277c-4a9a-b7ea-733ad21665a3)

I think this `Features, About Us, Contact, Privacy Policy`  row should be in one row in for mobile screen.   
In mobile screen it's unnecessarily wrapped and make one extra row. Which is looking bad for UI purpose.

### Steps to Reproduce

Check footer lower area in mobile screen.

### Expected Behavior

It should be in one line. That's make it more visually appealing.

### Screenshots or Logs (Optional)

![image](https://github.com/user-attachments/assets/6db4112a-2172-4ec8-b1d8-8173e361a134)

@ajay-dhangar  Please assign me this task. I think it's need improvement.

### Severity

Critical - prevents the use of the system

### Environment

- [X] Local Development
- [X] Staging
- [X] Production
- [ ] Other

**Comment by Suvadip-sana** [comment]
@ajay-dhangar   Could you please assign me this ISSUE. It's supposed to be fixed.

**Comment by ChetanSingh14** [comment]
@ajay-dhangar  please assign this issue to me .
