### ISSUE TITLE
[Feature Request] want to add document about shortest path algorithm

### ISSUE THREAD

**Issue by Kratik1093** [Ajay-Dhangar/algo#11]
---

**Would you like to work on this feature?**  
- [X] Yes  
- [ ] No

**Comment by code-killer0** [comment]
I want to add documentation part which include 
1. Dijkstra's Algorithm
2. Bellman-Ford Algorithm
3. Floyd-Warshall Algorithm
4. A* Algorithm

Kindly assign this issue to me.
