### ISSUE TITLE
[Feature Request]  Addition of Backtracking Algorithms 

### ISSUE THREAD

**Issue by Shariq2003** [Ajay-Dhangar/algo#111]
### Is your feature request related to a problem? Please describe.
Yes.
Addition of Most important topic, tracking algorithms. 
Many complex algorithmic problems such as N-Queens, Sudoku Solver, Subset Sum, and others require the use of backtracking algorithms. Without this addition, users are unable to explore these classical algorithms within the current repository.

### Describe the solution you'd like
I want to add backtracking algorithm concept in this and also its related problems as mentioned above.

---

**Would you like to work on this feature?**  
- [X] Yes  
- [ ] No

**Comment by ajay-dhangar** [comment]
@Shariq2003, thanks for your request to add backtracking algorithms to the algo repository. I've created a separate repository for backtracking algorithms. You can check it out at https://ajay-dhangar.github.io/backtracking/. I hope this helps!

**Comment by Shariq2003** [comment]
> @Shariq2003, thanks for your request to add backtracking algorithms to the algo repository. I've created a separate repository for backtracking algorithms. You can check it out at https://ajay-dhangar.github.io/backtracking/. I hope this helps!

Thanks, sir, I will check for sure.
