### ISSUE TITLE
[Feature Request]  Adding "TWO SUM" problem with Solution/explaination and PRACTICE LINK

### ISSUE THREAD

**Issue by Hamza1821** [Ajay-Dhangar/algo#124]
### Describe the solution you'd like
 Adding "TWO SUM" problem with Solution/explaination and PRACTICE LINK

### Additional context
Two sum problem is a standard array problem, favorite of many tech giants in their interview , adding this with a practice link can help user to learn this problem efficiently

---

**Would you like to work on this feature?**  

- [x] Yes  
- [ ] No  

###

**Comment by ajay-dhangar** [comment]
Hey @Hamza1821, I think you should check out https://codeharborhub.github.io/dsa/solutions/lc-solutions/0000-0099/two-sum. It provides a better understanding of the problem and makes it easier to write the code.

**Comment by Hamza1821** [comment]
Please clear my doubt:
do you want me to add two sum problem just like it is on this page 
https://codeharborhub.github.io/dsa/solutions/lc-solutions/0000-0099/two-sum

**Comment by Ruksina01** [comment]
Hello @ajay-dhangar ,
I am interested in this issue. Could you please assign it to me? Thank you!
