### ISSUE TITLE
Add More Problems to LeetCode 75 Section

### ISSUE THREAD

**Issue by tatheer-fathima** [Ajay-Dhangar/algo#1366]
### Idea Title

Add More Problems to LeetCode 75 Section

### Idea Description

The LeetCode 75 section currently has limited problems, and adding more questions would provide users with a broader range of topics to practice, especially for common interview patterns and core data structures.
![image](https://github.com/user-attachments/assets/0388c65a-909f-4c47-90c3-34b98ae446f5)

@ajay-dhangar I would like to work on it.
Please assign it to me under gssoc-ext and hacktoberfest.

### Potential Benefits

- [X] Improves user experience
- [X] Enhances learning
- [X] Adds a new feature
- [X] Improves code quality
- [ ] Other

**Comment by ajay-dhangar** [comment]
Our idea is to provide content that helps beginners learn about DSA and algorithms. For LeetCode problems and solutions, we already have other platforms.
