### ISSUE TITLE
[Feature]:Adding a valid anagram leetcode question 

### ISSUE THREAD

**Issue by VinayLodhi1712** [Ajay-Dhangar/algo#1372]
### Feature Name

Add valid anagram leetcode question in top dsa problems

### Feature Description

Add valid anagram leetcode question in top dsa problems
https://leetcode.com/problems/valid-anagram/?envType=study-plan-v2&envId=top-interview-150

### Motivation

Add valid anagram leetcode question in top dsa problems. It is asked in mosted interviews and it is leetcode 242 number question you can check

### Feature Type

New Algorithm

### Does this feature require additional resources?

- [ ] Additional Documentation
- [ ] Third-Party Libraries
- [ ] UI/UX Design
- [X] Other

### References (Optional)

leetcode 242

**Comment by ajay-dhangar** [comment]
Our idea is to provide content that helps beginners learn about DSA and algorithms. For LeetCode problems and solutions, we already have other platforms.
