### ISSUE TITLE
Graph Algorithms: Navigating Complex Relationships

### ISSUE THREAD

**Issue by SrijaVuppala295** [Ajay-Dhangar/algo#1509]

**Comment by SrijaVuppala295** [comment]
@ajay-dhangar , why its invalid ??

**Comment by ajay-dhangar** [comment]
We only need four PRs, and we don't want to open too many issues. Otherwise, it will start to feel like spam.

**Comment by SrijaVuppala295** [comment]
@ajay-dhangar , Bro I apologize I didnt know that , but atleast add level 1 label , to the remainning pr's

**Comment by SrijaVuppala295** [comment]
@ajay-dhangar , I didnt seen it was 200 points limit , atleast add upto the 200 points , and get merged !! Or shall i create a new 3 to 4 PRs , add upto 200 points
