### ISSUE TITLE
[Custom]: Change Logo to Match the One in the Footer

### ISSUE THREAD

**Issue by AnushkaChouhan25** [Ajay-Dhangar/algo#1538]
### Issue Summary

Change Logo of Navbar to Match the Footer logo

### Issue Description

Update the header logo to align with the design and style of the footer logo for visual consistency across the website. Ensure the size, color, and theme are consistent with the footer's appearance.

![image](https://github.com/user-attachments/assets/6d351043-ff76-46cf-bdbf-a0efd8a0f6c0)

### Priority

High - Requires urgent attention

### Category

- [X] Enhancement
- [X] Refactor
- [ ] Security
- [X] Design
- [ ] Other

**Comment by VijeshVS** [comment]
Hey @ajay-dhangar ,
I would like to work on this issue. Could you pls assign this issue to me
Thank you.
