### ISSUE TITLE
Reduce the Size of the Contributor Section 

### ISSUE THREAD

**Issue by AnushkaChouhan25** [Ajay-Dhangar/algo#1539]
Modify the Contributor Section to display smaller profile cards, allowing more contributors to be visible at once.

![image](https://github.com/user-attachments/assets/8ee3bfac-1ce4-4708-9395-947989afaa17)

**Comment by VijeshVS** [comment]
Hey @ajay-dhangar ,
I would like to work on this issue. Could you pls assign this issue to me
Thank you.
