### ISSUE TITLE
Automation of project structure updation using GitHub workflows and Python scripts

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [Ajay-Dhangar/algo#1616]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/ajay-dhangar/algo/blob/main/CONTRIBUTING.md).

### Description

# Description

Currently, the project doesn't have a **project structure**. And, it would be a bit difficult for newcomers to understand the project structure completely. Also, it's difficult for anyone to manually change the project structure as it grows in size day by day. So, automating this with GitHub workflows and Python script will make the maintenance easier.

I want to add a **detailed project structure** in a separate file(redirect in README.md) for the contributors to refer to and **automate its updation process** as new files are added in the projects. This will help them refer to the structure and will make it easier for them to understand.

# Screenshots

Sample of how the workflow would be automated and the project structure after updation in readme:
![image](https://github.com/user-attachments/assets/81e8ca29-70d3-421e-aabc-1a2e428f13d5)

![image](https://github.com/user-attachments/assets/0bc44243-5a2a-4e6e-8afc-e0dd9097515f)

I am willing to work on this issue. Please assign me the issue

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by rajdeepchakraborty-rc** [comment]
This is a kind of enhancement, but I think it might be labeled as documentation. I am not sure whether the label I added is ok. Please excuse me for that.

**Comment by rajdeepchakraborty-rc** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by ajay-dhangar** [comment]
Follow

![image](https://github.com/user-attachments/assets/ec7c9448-8f94-474c-bd4d-b4818f572fa4)

**Comment by rajdeepchakraborty-rc** [comment]
@ajay-dhangar Why did you unassign me and close the issue?
