### ISSUE TITLE
[Idea]: Add Projects

### ISSUE THREAD

**Issue by purnima2904** [Ajay-Dhangar/algo#1668]
### Idea Title

Create a folder for projects

### Idea Description

Adding projects in various languages like c++ , java , python , web dev. etc.

kindly assign this issue under gssoc with level label 3

### Potential Benefits

- [X] Improves user experience
- [X] Enhances learning
- [X] Adds a new feature
- [ ] Improves code quality
- [X] Other

### Implementation Suggestions (Optional)

adding code for every project ( language specific)

i will implement 2 projects per language.
1 beginner and 1 advanced

**Comment by ajay-dhangar** [comment]
We need only projects based on DSA, so only use DSA-based projects. If you have a project that is not DSA-based, please convert it to DSA-based.
