### ISSUE TITLE
[New Algorithm]: <Optimal Merge Pattern> in Greedy Algorithm

### ISSUE THREAD

**Issue by shuvojitss** [Ajay-Dhangar/algo#1710]
### Idea Title

Optimal Merge Pattern

### Name:
Merge a set of sorted files of different length into a single sorted file. We need to find an optimal solution, where the resultant file will be generated in minimum time. Use greedy approach to solve this.

### About:
Implementation of Greedy Algorithm.

### Input:
An array containing lenght of each file

### Output:
Minimum cost of merging 

### Potential Benefits

- [X] Improves user experience
- [X] Enhances learning
- [X] Adds a new feature
- [X] Improves code quality
- [X] Other

### Potential Benefits

- [X] Improves user experience
- [X] Enhances learning
- [X] Adds a new feature
- [X] Improves code quality
- [X] Other

**Comment by Sai-ganesh-0004** [comment]
i would like to contribute
