### ISSUE TITLE
Update stargazers

### ISSUE THREAD

**Issue by yashksaini-coder** [Ajay-Dhangar/algo#1714]
I would like to update and make UI changes to the Stargazers component in the main Home page 

@ajay-dhangar can you assign this issue to me

**Comment by ajay-dhangar** [comment]
can you share one demo

**Comment by yashksaini-coder** [comment]
> can you share one demo

I meant updating the current, as your project is getting popular a lot very quickly, so the current asset video i had created is already outdated, that's why I mean to update the current one 
because the video is generated through the remotion lib, I still haven't figured out a solution to automate the updation of the asset video

**Comment by yashksaini-coder** [comment]
@ajay-dhangar also message you on discord, for previous PR review

**Comment by yashksaini-coder** [comment]
closing as the original component deleted, thx for your time
