### ISSUE TITLE
[Custom]:  <ADD A PROBLEM> Subarray Sum Equals K to practice skills section

### ISSUE THREAD

**Issue by shriyadindi** [Ajay-Dhangar/algo#1771]
### Issue Summary

Subarray Sum Equals K

### Issue Description

Subarray Sum Equals K

Problem: Given an array of integers and an integer k, find the number of continuous subarrays whose sum equals k.
Hint: Use a hashmap to store cumulative sums and their counts for efficient lookup.

### Priority

High - Requires urgent attention

### Category

- [ ] Enhancement
- [ ] Refactor
- [ ] Security
- [ ] Design
- [ ] Other

**Comment by ajay-dhangar** [comment]
@shriyadindi, Please only open four PRs and issues at a time, or they will not be considered for evaluation.
