### ISSUE TITLE
[Custom]:  <ADD A PROBLEM>Find All Anagrams in a String to practice skills section 

### ISSUE THREAD

**Issue by shriyadindi** [Ajay-Dhangar/algo#1772]
### Issue Summary

Find All Anagrams in a String

### Issue Description

Find All Anagrams in a String
Problem: Given a string s and a non-empty string p, find all the start indices of p's anagrams in s.
Hint: Sliding window approach with character count comparison can help solve this efficiently.

### Priority

High - Requires urgent attention

### Category

- [ ] Enhancement
- [ ] Refactor
- [ ] Security
- [ ] Design
- [x] Other

**Comment by ajay-dhangar** [comment]
@shriyadindi, Please only open four PRs and issues at a time, or they will not be considered for evaluation.
