### ISSUE TITLE
[Feature]: Add scroll to top button

### ISSUE THREAD

**Issue by souvikpramanikgit** [Ajay-Dhangar/algo#1779]
### Feature Name

Add scroll to top button

### Feature Description

I want to add scroll to top button which can be applicable in every page.

### Motivation

Give you quick access to the main navigation or search bar, so you can get where you need faster.

### Implementation Suggestions (Optional)

Because not all pages have this button,like this
![image](https://github.com/user-attachments/assets/035d562b-d500-4a48-8ae3-0d61cab86d08)

### Feature Type

UI/UX Improvement

### Does this feature require additional resources?

- [ ] Additional Documentation
- [ ] Third-Party Libraries
- [X] UI/UX Design
- [ ] Other

**Comment by ajay-dhangar** [comment]
This feature is not ready for use. We need to make it better after this program is completed. Some contributors have created bugs and not follow rules, so we need to reset our UI/UX and code base.
