### ISSUE TITLE
[Custom]: <ADD A PROBLEM> Word Ladder II to Top DSA interview questions 

### ISSUE THREAD

**Issue by shriyadindi** [Ajay-Dhangar/algo#1783]
### Issue Summary

Word Ladder II

### Issue Description

Given two words (beginWord and endWord), and a dictionary's word list, find all the shortest transformation sequences from beginWord to endWord. Each transformed word must exist in the word list.

### Priority

High - Requires urgent attention

### Category

- [ ] Enhancement
- [ ] Refactor
- [ ] Security
- [ ] Design
- [ ] Other

**Comment by ajay-dhangar** [comment]
@shriyadindi, Please only open four PRs and issues at a time, or they will not be considered for evaluation.
