### ISSUE TITLE
[Custom]: <ADD A PROBLEM>Minimum Number of Days to Make m Bouquets to Top DSA interview questions 

### ISSUE THREAD

**Issue by shriyadindi** [Ajay-Dhangar/algo#1784]
### Issue Summary

Minimum Number of Days to Make m Bouquets

### Issue Description

Problem: You are given an integer array bloomDay, an integer m, and an integer k. You need to find the minimum number of days required to make m bouquets. Each bouquet can be made up of k flowers.

### Priority

High - Requires urgent attention

### Category

- [ ] Enhancement
- [ ] Refactor
- [ ] Security
- [ ] Design
- [ ] Other

**Comment by ajay-dhangar** [comment]
@shriyadindi, Please only open four PRs and issues at a time, or they will not be considered for evaluation.
