### ISSUE TITLE
[Custom]: <ADD A PROBLEM>Split Array Largest Sum to Top DSA interview questions 

### ISSUE THREAD

**Issue by shriyadindi** [Ajay-Dhangar/algo#1785]
### Issue Summary

Split Array Largest Sum

### Issue Description

Problem: Given an array and an integer k, split the array into k non-empty continuous subarrays such that the largest sum of any subarray is minimized. Return this minimized largest sum.

### Priority

High - Requires urgent attention

### Category

- [ ] Enhancement
- [ ] Refactor
- [ ] Security
- [ ] Design
- [ ] Other

**Comment by ajay-dhangar** [comment]
@shriyadindi, Please only open four PRs and issues at a time, or they will not be considered for evaluation.

**Comment by shriyadindi** [comment]
@ajay-dhangar okay
