### ISSUE TITLE
[Idea]: Merge Two Sorted List

### ISSUE THREAD

**Issue by SKG24** [Ajay-Dhangar/algo#1805]
### Idea Title

Merge Two Sorted List | Linked List

### Idea Description

Merge the two lists into one sorted list. The list should be made by splicing together the nodes of the first two lists.
We are supposed to return the head of the merged linked list.

Input: list1 = [1,2,4], list2 = [1,3,4]
Output: [1,1,2,3,4,4]

Participation: gssoc-ext

### Potential Benefits

- [ ] Improves user experience
- [ ] Enhances learning
- [X] Adds a new feature
- [ ] Improves code quality
- [ ] Other

**Comment by sujitgunjal** [comment]
Hello
Do i have to create a new file e.g. mergeLL.md and add the code for merging two LL
