### ISSUE TITLE
Automate Contributors List and Add Scroller to README

### ISSUE THREAD

**Issue by neeru24** [Ajay-Dhangar/algo#1953]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/ajay-dhangar/algo/blob/main/CONTRIBUTING.md).

### Description
The current README has a manually updated contributors list, which requires frequent updates and makes the README appear bulky. To improve this, we need to:

1. **Automate the contributors list** so it dynamically updates whenever a new contributor joins.
2. **Add a horizontal scroller** to display contributors in a compact, visually appealing way.

### Goals
- **Dynamically update contributors** in the README to avoid manual maintenance.
- **Implement a scroller** for the contributors section to keep the README organized and prevent it from being overcrowded.

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by ajay-dhangar** [comment]
@neeru24, can you share a simple demo?

**Comment by neeru24** [comment]
> @neeru24, can you share a simple demo?

Sure, I have attached an image in the PR for this issue. You can check out
