### ISSUE TITLE
[Feature Request] Binary Search

### ISSUE THREAD

**Issue by AnujSaha0111** [Ajay-Dhangar/algo#203]
### It is an important algorithm in data structure, which is also used in several high level programs

---

**Would you like to work on this feature?**  
- [x] Yes  
- [ ] No  

Can you please assign it to me? and also add the gssoc-ext label

**Comment by KomalKalra05** [comment]
Can you please assign this to me I want to work on it

**Comment by AnujSaha0111** [comment]
Solved it #230
