### ISSUE TITLE
Practice Problems for Binary Search

### ISSUE THREAD

**Issue by samar12-rad** [Ajay-Dhangar/algo#237]
Title: Create a Section for Practice Problems on Binary Search

Description:

Develop a comprehensive list of practice problems focused on binary search algorithms.
Include a variety of problem types to cater to different skill levels, such as:
Basic binary search problems on sorted arrays.
Applications of binary search in finding the first/last occurrence of an element.
Problems involving searching in rotated sorted arrays.
Challenges requiring binary search on the answer (e.g., finding the square root, searching in a matrix).
Advanced problems like finding the peak element in an array or solving optimization problems using binary search.
Provide clear problem statements, example inputs and outputs, and hints or solutions where applicable.
Acceptance Criteria:

The section should contain at least 10 distinct binary search practice problems.
Each problem should include a clear description, examples, and expected outcomes.
Solutions or hints should be provided for each problem to assist learners.

**Comment by Ruksina01** [comment]
Hello @ajay-dhangar 

I am interested in this issue. Could you please assign it to me? Thank you!

**Comment by samar12-rad** [comment]
@ajay-dhangar , i am doing it
