### ISSUE TITLE
Practice Problems for Greedy Algorithms

### ISSUE THREAD

**Issue by samar12-rad** [Ajay-Dhangar/algo#240]
Title: Create a Section for Practice Problems on Greedy Algorithms

Description:

Develop a comprehensive list of practice problems focused on greedy algorithms.
Include a variety of problem types to cover different applications of greedy techniques, such as:
Activity selection problems (e.g., scheduling activities).
Coin change problems (e.g., making change with the minimum number of coins).
Huffman coding (building optimal prefix codes).
Minimum spanning tree problems (e.g., Prim's and Kruskal's algorithms).
Job sequencing problems (maximizing profit with deadlines).
Fractional knapsack problem (maximizing value for a given weight).
Optimal merge patterns (merging files with minimum cost).
Provide clear problem statements, example inputs and outputs, and hints or solutions where applicable.
Acceptance Criteria:

The section should contain at least 10 distinct practice problems related to greedy algorithms.
Each problem should include a clear description, examples, and expected outcomes.
Solutions or hints should be provided for each problem to assist learners.

**Comment by ajay-dhangar** [comment]
@samar12-rad, please limit the creation of issues to 4 per day, or focus on working on 4 existing issues. This helps avoid confusion and ensures efficient collaboration.

**Comment by samar12-rad** [comment]
ok @ajay-dhangar
