### ISSUE TITLE
Practice Problems for Combinatorics

### ISSUE THREAD

**Issue by samar12-rad** [Ajay-Dhangar/algo#242]
Title: Create a Section for Practice Problems on Combinatorics

Description:

Develop a comprehensive list of practice problems focused on combinatorics.
Include a variety of problem types to cover different aspects of combinatorial mathematics, such as:
Counting principles (e.g., permutations and combinations).
Problems involving the binomial theorem.
Applications of combinatorics in probability.
The pigeonhole principle.
Graph theory problems related to counting paths and cycles.
Problems on generating functions.
Applications of combinatorics in game theory and optimization.
Provide clear problem statements, example inputs and outputs, and hints or solutions where applicable.
Acceptance Criteria:

The section should contain at least 10 distinct combinatorics practice problems.
Each problem should include a clear description, examples, and expected outcomes.
Solutions or hints should be provided for each problem to assist learners.

**Comment by ajay-dhangar** [comment]
@samar12-rad, please limit the creation of issues to 4 per day, or focus on working on 4 existing issues. This helps avoid confusion and ensures efficient collaboration.
