### ISSUE TITLE
[Bug] Errors while running the npm start

### ISSUE THREAD

**Issue by monishkumardvs** [Ajay-Dhangar/algo#275]
### Describe the bug
lot of errors

r

### Expected behavior
can u assign me i will create the website without errors
Give me lvl 3 i will work on it
### Screenshots
![image](https://github.com/user-attachments/assets/4747b91e-bce5-41c8-9d18-0f20ae96ce40)

**Would you like to work on this issue?**  
- [ x] Yes  
- [ ] No

**Comment by ajay-dhangar** [comment]
already solved this error
