### ISSUE TITLE
Add Crousel

### ISSUE THREAD

**Issue by shubhagarwal1** [Ajay-Dhangar/algo#277]
<img width="1417" alt="Screenshot 2024-10-08 at 4 55 36 PM" src="https://github.com/user-attachments/assets/828125b4-660c-4271-911c-8b39807c0820">
Implement a carousel feature on the page to display media or content in a rotating fashion. The carousel should support:

Multiple slides with image and text content.
User controls (next/prev buttons, indicators).
Optional autoplay feature with adjustable interval.
Responsiveness for mobile and desktop views.
Hey @ajay-dhangar can you please assign me this task .

**Comment by ajay-dhangar** [comment]
Our site does not need a carousel feature for the Hero section. The Hero section is the first thing that users see when they land on the site. It should be visually appealing and provide users with a clear understanding of what the site is about. A carousel feature would distract users from the main message of the Hero section.

**Comment by shubhagarwal1** [comment]
> Our site does not need a carousel feature for the Hero section. The Hero section is the first thing that users see when they land on the site. It should be visually appealing and provide users with a clear understanding of what the site is about. A carousel feature would distract users from the main message of the Hero section.

i can add crousel to the landning page then not to the hero section but to any other part this would increase use interactivity witht he page
