### ISSUE TITLE
[Feature Request] Addition of Leetcode 21-30 questions and their Solutions

### ISSUE THREAD

**Issue by IkkiOcean** [Ajay-Dhangar/algo#297]
Description:
This issue proposes adding the solutions and explanations for LeetCode questions 21-30 to the repository. This addition will enhance our collection of coding challenges and provide valuable resources for users looking to improve their problem-solving skills.

This will include: 
- Question Title
- Problem Description
- Example(s)
- Solution
- Explanation
- Time and Space Complexity Analysis

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
I would like to work on this
