### ISSUE TITLE
[Feature Request] Practice problems for Linked List

### ISSUE THREAD

**Issue by 17arindam** [Ajay-Dhangar/algo#307]
### Is your feature request related to a problem? Please describe.
currently there are no problems of Linked list 

### Describe the solution you'd like
problems increase the topics understanding and hep us very much 

### Describe alternatives you've considered
i want to add linked list questions document 

### Additional context
![image](https://github.com/user-attachments/assets/c4dda0f5-e27b-4d80-ab4d-1187756305c7)

---

**Would you like to work on this feature?**  
- [x] Yes  
- [ ] No

**Comment by 17arindam** [comment]
@ajay-dhangar please assign me this issue

**Comment by iking07** [comment]
It's already done!
