### ISSUE TITLE
[Feature Request] Addition of 21-40 Questions of Leetcode in Leetcode Solutions Sections.

### ISSUE THREAD

**Issue by Shariq2003** [Ajay-Dhangar/algo#309]
### Is your feature request related to a problem? Please describe.
Addition of 20 questions solutions in depth in Leetcode solutions sections.

---

**Would you like to work on this feature?**  
- [X] Yes  
- [ ] No

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
I would like to work on this
