### ISSUE TITLE
Copyright is not alligned properly 

### ISSUE THREAD

**Issue by Anjalis14** [Ajay-Dhangar/algo#318]
## 📋 General Issue or Question
The copy right is not alligned properly it should be centered 

![image](https://github.com/user-attachments/assets/55e3274b-4a1b-49bb-8a17-e9db74676f18)

**Would you like to work on this issue?**  
- [x] Yes  
- [ ] No

**Comment by Anjalis14** [comment]
@ajay-dhangar  please assign me this

**Comment by ajay-dhangar** [comment]
Can you explain why you want the copyright notice to be centered? Do you have any ideas or examples of how this could be done? Please share them.

**Comment by Anjalis14** [comment]
according to the idea of the website and the UI  copyright should be in the
center as it is in the right corner it is not properly / directly viewed by
the user so for the users view it should be in white colour and center

**Comment by ajay-dhangar** [comment]
I think you can use any footer template in tsx with tailwind CSS for our Algo. However, it needs to be properly matched to our site.

**Comment by ajay-dhangar** [comment]
Our current footer works well for now, but we may need to update it to accommodate future ideas. Feel free to suggest any design improvements based on your code. I’m also available to assist with the update if needed.
