### ISSUE TITLE
[Enhancement Request] Giving tabs to switch between code samples instead of showing the code in front 

### ISSUE THREAD

**Issue by KunikaMakker** [Ajay-Dhangar/algo#322]
## 🚀 Enhancement Request

Currently, code snippets of C++ and Python are visible directly on the page. So, if we plan to add more language code snippets, the pages might look lengthy. Instead, we can use the tabs-like structure, similar to another coding platform. So user will not have to scroll so much to get to his/her preferred language.
Current view
<img width="839" alt="Screenshot 2024-10-09 at 7 22 58 AM" src="https://github.com/user-attachments/assets/6c42f3ba-fb06-4cf6-a2ad-787ce297e21b">

Enhanced view can be similar to 
<img width="535" alt="Screenshot 2024-10-09 at 7 29 28 AM" src="https://github.com/user-attachments/assets/a12f3482-2d2e-4ca5-975b-3572f2584a9b">
 
---

**Would you like to work on this feature?**  
- [x] Yes  
- [ ] No

**Comment by ajay-dhangar** [comment]
@KunikaMakker, this looks great! Here's a structured approach you can follow for adding code snippets in different languages using **Tabs**:

```md
<Tabs>
  <TabItem value="js" label="JavaScript" default>
    ```js
    // Write your JavaScript code here
    ```
  </TabItem>
  
  <TabItem value="java" label="Java">
    ```java
    // Write your Java code here
    ```
  </TabItem>
  
  <TabItem value="py" label="Python">
    ```py
    # Write your Python code here
    ```
  </TabItem>
</Tabs>
```

This allows you to neatly organize code snippets by language, making them easily accessible.
