### ISSUE TITLE
[Leetcode 31-40]: Add Leetcode Questions 31 to 40 Detailed Solution with Code

### ISSUE THREAD

**Issue by SAMluci666** [Ajay-Dhangar/algo#362]
## 🚀 Feature Request
I am contributing so that people can have a place for finding all the solutions for Leetcode Problems.

### LeetCode Questions Checklist

- [ ] **31. Next Permutation**
- [ ] **32. Longest Valid Parentheses**
- [ ] **33. Search in Rotated Sorted Array**
- [ ] **34. Find First and Last Position of Element in Sorted Array**
- [ ] **35. Search Insert Position**
- [ ] **36. Valid Sudoku**
- [ ] **37. Sudoku Solver**
- [ ] **38. Count and Say**
- [ ] **39. Combination Sum**
- [ ] **40. Combination Sum II**

### Additional context
As I'll be contributing detailed solutions with code and necessary diagrams for 10 Leetcode Questions covering topics like DP, Arrays
and backtracking etc.
- @ajay-dhangar  Please assign this issue to me with  level 2 GSSOC-EXT and Hacktoberfest Tags. 
---
##Thank you!
**Would you like to work on this feature?**  
- [x] Yes  
- [ ] No

**Comment by ajay-dhangar** [comment]
@SAMluci666, we have already covered all problems in https://codeharborhub.github.io/dsa/problems/leetcode-problems/0000-0099 and solutions in https://codeharborhub.github.io/dsa/solutions/category/leetcode-solutions.

**Comment by SAMluci666** [comment]
@ajay-dhangar 
Does the "<table" and "{" that appears on the cards page a bug? If yes I can solve that as well as whenever I click on the solution I get page not found https://codeharborhub.github.io/dsa-solutions/lc-solutions/0000-0099/two-sum 

![image](https://github.com/user-attachments/assets/67fe1eab-fcd5-45c1-85e9-a2109fbadebf)
