### ISSUE TITLE
[Bug] Broken image in footer

### ISSUE THREAD

**Issue by devarsheecodess** [Ajay-Dhangar/algo#374]
### Describe the bug
In footer, the logo is broken

### Screenshots
![image](https://github.com/user-attachments/assets/efdc3276-0862-47d2-9777-840150bdd021)

**Would you like to work on this issue?**  
- [x] Yes  
- [ ] No

**Comment by devarsheecodess** [comment]
@ajay-dhangar assign me this task under gssoc-ext, hacktoberfest-accepted and level1 label

**Comment by ajay-dhangar** [comment]
image is already working
