### ISSUE TITLE
[Feature Request] <Title of your feature>

### ISSUE THREAD

**Issue by shanmukhi-developer** [Ajay-Dhangar/algo#398]
### Is your feature request related to a problem? Please describe.
Solution for the leet code problems are provided in python and c++.

### Describe the solution you'd like
I want to add Java solutions for Leetcode problems 11-20.

---

**Would you like to work on this feature?**  
- [ * ] Yes  
- [ ] No

**Comment by ajay-dhangar** [comment]
Can you work on other issues

**Comment by shanmukhi-developer** [comment]
Yes, I can work. can you please assign me ?
