### ISSUE TITLE
[Feature Request] Adding all algorithms related to graphs

### ISSUE THREAD

**Issue by nishakp3005** [Ajay-Dhangar/algo#41]
### Adding visual learning images, to help grasp the concept better.

---

**Would you like to work on this feature?**  
- [x] Yes  

@ajay-dhangar please assign me this issue

**Comment by sriparna-18** [comment]
I have studied graphs algorithms in detail, please assign me this issue.

**Comment by nishakp3005** [comment]
@sriparna-18 you can help in some other data structure, I have already added those algorithms and detailed explanation as well.
