### ISSUE TITLE
[Bug] Same Codes Multiple times 

### ISSUE THREAD

**Issue by RanaJay3101** [Ajay-Dhangar/algo#422]
### Describe the bug
There is a duplicate section of content displayed on the website. The "Easy array leetcode problems 10" is repeated twice under the LeetCode Solutions category, which leads to redundant information being shown.

### To Reproduce
1. Go to the "LeetCode Solutions" section.
2. Click on the dropdown to reveal the "Easy array leetcode problems 10" section.
3. Click on the dropdown to reveal the "LeetCode Solutions 1-10" section" section.
4. Notice that this section appears twice in the list, leading to a redundant display.

### Expected behavior
Only one section titled "LeetCode Solutions 1-10" should be shown.

### Screenshots
![image](https://github.com/user-attachments/assets/c08ecf6e-2ff1-400a-8879-828a68cafc4f)

---

**Would you like to work on this issue?**  
- [x] Yes  
- [ ] No

**Comment by ajay-dhangar** [comment]
@RanaJay3101, please don't work on this issue. I need to delete this issue and rewrite the structure with formatting.
