### ISSUE TITLE
Enhancement of footer

### ISSUE THREAD

**Issue by Kajalmehta29** [Ajay-Dhangar/algo#435]
I want to make some changes in the footer section to enhance it. 

Please assign this issue to me under gssoc-extd and hacktoberfest.

**Comment by ajay-dhangar** [comment]
can you explain more about your issue

**Comment by Kajalmehta29** [comment]
current footer is kind of looking scattered. I want to place everything in a systematic way that will look good and attractive too.

**Comment by Kajalmehta29** [comment]
@ajay-dhangar  Can i do it in html and css? or i have to go for typescript only?
