### ISSUE TITLE
add Managers with at Least 5 Direct SQL Leetcode question  Solution

### ISSUE THREAD

**Issue by shravya312** [Ajay-Dhangar/algo#437]
### Issue Description
I want to add Managers with at Least 5 Direct SQL Leetcode question  Solution
### Additional Context
Add any other context, code snippets, or screenshots related to the issue or question.

---

**Would you like to work on this issue?**  
- [x] Yes  
- [ ] No

**Comment by shravya312** [comment]
Hi @ajay-dhangar can u assign this issue to me

**Comment by ajay-dhangar** [comment]
We are not working on LeetCode solutions. We only provide DSA solutions for better understanding. For example, see https://ajay-dhangar.github.io/algo/docs/basic-dsa/array/arrays-in-dsa.

**Comment by shravya312** [comment]
Okay fine got it 😇
