### ISSUE TITLE
Add leetcode 21 to 30 solution

### ISSUE THREAD

**Issue by kRajoria121** [Ajay-Dhangar/algo#448]
### Is your feature request related to a problem? Please describe.
Wanted to add leetcode solution from 21 to 30
---

**Would you like to work on this feature?**  
- [ ] Yes

**Comment by ajay-dhangar** [comment]
We don't need to provide leetcode problems and solutions at this time because we've already created a separate site for them. You can check it out at https://codeharborhub.github.io/dsa/problems/category/leetcode-problems.

**Comment by kRajoria121** [comment]
what can i contribute?
