### ISSUE TITLE
ADD leetcode 31 to 40 solution with TC and SC

### ISSUE THREAD

**Issue by kRajoria121** [Ajay-Dhangar/algo#449]
### Is your feature request related to a problem? Please describe.
wanted to add leetcode solution in cpp and python

---

**Would you like to work on this feature?**  
- Yes

**Comment by ajay-dhangar** [comment]
We don't need to provide leetcode problems and solutions at this time because we've already created a separate site for them. You can check it out at https://codeharborhub.github.io/dsa/problems/category/leetcode-problems.
