### ISSUE TITLE
[Feature Request] Adding multiple languages in Leetcode Solution

### ISSUE THREAD

**Issue by KunikaMakker** [Ajay-Dhangar/algo#451]
### Is your feature request related to a problem? Please describe.
For now we only have solutions for C++ and Python

### Describe the solution you'd like
For now we only have solutions for C++ and Python, we can consider adding other languages too, like C, Java, Javascript, and Typescript.
If any other language is needed, we can do that too.
If its okay, we can also decide which language will be default and what will be the sequence of the languages

---

**Would you like to work on this feature?**  
- [x] Yes  
- [ ] No

**Comment by ajay-dhangar** [comment]
We don't need to provide leetcode problems and solutions at this time because we've already created a separate site for them. You can check it out at https://codeharborhub.github.io/dsa/problems/category/leetcode-problems.
