### ISSUE TITLE
[General] LeetCode 75 Qs

### ISSUE THREAD

**Issue by aditiverma-21** [Ajay-Dhangar/algo#453]
The solution to the questions in Ace Coding Interview with 75 Qs in LeetCode

**Comment by ajay-dhangar** [comment]
@aditiverma-21, you need to follow our structure like https://ajay-dhangar.github.io/algo/dsa-roadmap

**Comment by aditiverma-21** [comment]
@ajay-dhangar okay I will be adding 75 solutions of leetcode's ace interview in 75 days in the leetcode folder
