### ISSUE TITLE
[Feature Request] <Add redirections to leetcode questions>

### ISSUE THREAD

**Issue by PavanTeja2005** [Ajay-Dhangar/algo#467]
### Is your feature request related to a problem? Please describe.
There are no links to the leetcode question sites but there are solutions. Those links would let users redirect directly to the leetcode question site and run them immediately without explicitly searching.
Hence adding them will add a great advantage to the users.

### Describe the solution you'd like
I would like to add all the links to all 40 leetcodes questions which are there in the site now.

### Describe alternatives you've considered
none

### Additional context

---

**Would you like to work on this feature?**  
- [x] Yes  
- [ ] No

**Comment by ajay-dhangar** [comment]
We don't need to provide leetcode problems and solutions at this time because we've already created a separate site for them. You can check it out at https://codeharborhub.github.io/dsa/problems/category/leetcode-problems.
