### ISSUE TITLE
 Product of Array Except Self dsa problem solution

### ISSUE THREAD

**Issue by shravya312** [Ajay-Dhangar/algo#468]
### Issue Description
Product of Array Except Self dsa problem solution

### Additional Context
Add any other context, code snippets, or screenshots related to the issue or question.

---

**Would you like to work on this issue?**  
- [x] Yes  
- [ ] No

**Comment by Ruksina01** [comment]
Hello @ajay-dhangar,

I am interested in this issue. Could you please assign it to me? Thank you!
