### ISSUE TITLE
[Feature Request] No Quiz Questions and results on binary trees

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [Ajay-Dhangar/algo#475]
### Is your feature request related to a problem? Please describe.
No quiz questions on binary trees

### Describe the solution you'd like
Quiz enhances and builds confidance on solving questions

### Describe alternatives you've considered
creates quiz and provide result

### Additional context

---

**Would you like to work on this feature?**  
- [x] Yes  
- [ ] No

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
Want to work on this issue

**Comment by ajay-dhangar** [comment]
Please don't create spam. We need only four issues open, not a large number. If you want to work on more issues, you can try other open source projects. A large number of issues in a single project can create problems for you and for us.
