### ISSUE TITLE
[Feature Request] conduct quiz on binary search tree

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [Ajay-Dhangar/algo#477]
### Is your feature request related to a problem? Please describe.
conduct quiz on binary search tree

### Describe the solution you'd like
 quiz increases confidence in coder to learn from mistakes conduct quiz on binary search tree
### Describe alternatives you've considered
conduct quiz on binary search tree
### Additional context

---

**Would you like to work on this feature?**  
- [ ] Yes  
- [ ] No

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
want to work on this issue

**Comment by ajay-dhangar** [comment]
Please don't create spam. We need only four issues open, not a large number. If you want to work on more issues, you can try other open source projects. A large number of issues in a single project can create problems for you and for us.
