### ISSUE TITLE
[Feature Request] Add Double ended queue and more complex sorting algorithms

### ISSUE THREAD

**Issue by pavitraag** [Ajay-Dhangar/algo#50]
## 🚀 Feature Request

I would like to add Double ended queue and more complex sorting algorithms

---

**Would you like to work on this feature?**  
- [X] Yes  
- [ ] No

**Comment by iking07** [comment]
@ajay-dhangar sir can i be assigned this dequeue(Double-ended queue) blog as I have added the Problem sets but blog isn't there
