### ISSUE TITLE
[Feature Request] : Adding Bellman-Ford Algorithm.

### ISSUE THREAD

**Issue by AbhijitMotekar99** [Ajay-Dhangar/algo#525]
### Is your feature request related to a problem? Please describe.
I'm frustrated when I need to find the shortest path in a graph with negative weight edges, but there’s no implementation of the Bellman-Ford algorithm available.

### Describe the solution you'd like
The addition of the Bellman-Ford Algorithm documentation and code implementation, which efficiently computes shortest paths from a single source node to all other nodes in a graph, even when negative weight edges are present. It should include an explanation of how the algorithm works, its time complexity, and an example use case.

### Describe alternatives you've considered
Alternatives include using Dijkstra's Algorithm, but Bellman-Ford is more suitable for graphs with negative weight edges, where Dijkstra's algorithm fails.

### Additional context
Add real-world applications where the Bellman-Ford algorithm is used (e.g., detecting negative cycles in currency exchange rates) and a complete code implementation with examples.

**Would you like to work on this feature?**  
- [x] Yes  
- [ ] No

**Comment by Ruksina01** [comment]
Hello @ajay-dhangar ,

I am interested in this issue. Could you please assign it to me? Thank you!
