### ISSUE TITLE
[Bug] : There is nothing inside Programming Fundamentals section, adding fundamentals.

### ISSUE THREAD

**Issue by AbhijitMotekar99** [Ajay-Dhangar/algo#526]
### Describe the bug
The Programming Fundamentals section is empty or incomplete, lacking any relevant content or documentation. This creates confusion and doesn't provide the necessary information.

### To Reproduce

1. Go to the 'Programming Fundamentals' section.
2. Click on it to view the content.
3. Notice that there is no information or content inside the section.

### Expected behavior
The Programming Fundamentals section should contain comprehensive information on basic programming concepts such as variables, loops, conditionals, functions, and data structures.

### Additional context
This section is crucial for beginners, so it needs to be populated with well-structured, beginner-friendly content and examples for a variety of programming languages.

**Would you like to work on this issue?**  
- [x] Yes  
- [ ] No

**Comment by Ruksina01** [comment]
Hello @ajay-dhangar ,

I am interested in this issue. Could you please assign it to me? Thank you!

**Comment by ajay-dhangar** [comment]
Thank you for your interest in working on this issue. @Ruksina01 and @AbhijitMotekar99, this issue has several different topics that need to be addressed. Please let me know which topics you would like to work on.

**Comment by Ruksina01** [comment]
@ajay-dhangar , 
I understand that the course topics are vast, so I think starting with these foundational concepts is the best approach.
Topics such as variables, loops, and conditionals.
I wanted to clarify in what format I should present these topics. Should I choose a specific programming language to focus on, or would an overview of these concepts suffice?

**Comment by AbhijitMotekar99** [comment]
Hey @ajay-dhangar 
In the programming fundamentals section, I will be working on basic programming concepts such as variables, loops, conditionals, functions, and data structures.
