### ISSUE TITLE
[Feature Request] Add LinkedList implementation

### ISSUE THREAD

**Issue by shalini-bhandari** [Ajay-Dhangar/algo#53]
## 🚀 Feature Request
LinkedList is another important data structure to learn and hence should be added.
Adding visual learning images, to help grasp the concept better.

---

**Would you like to work on this feature?**  
- [ ] Yes  
kindly assign me this issue under gssoc-ext and hacktoberfest-accepted with appropriate level

**Comment by AnujSaha0111** [comment]
I want to work on it. Can you please assign it to me?
