### ISSUE TITLE
[Feature Request] <Title of your feature>Ui enhancement

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [Ajay-Dhangar/algo#535]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. Example: "I'm frustrated when..."

### Additional context

---

**Would you like to work on this feature?**  
- [ ] Yes  
- [ ] No

**Comment by ajay-dhangar** [comment]
Please don't create spam. We need only four issues open, not a large number. If you want to work on more issues, you can try other open source projects. A large number of issues in a single project can create problems for you and for us.
