### ISSUE TITLE
[Feature Request] <Title of your feature>Update footer

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [Ajay-Dhangar/algo#537]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. Example: "I'm frustrated when..."

### Additional context

---

**Would you like to work on this feature?**  
- [ ] Yes  
- [ ] No

**Comment by ajay-dhangar** [comment]
Can you describe the issues you're having with the footer?

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
Sorry it is by mistake
