### ISSUE TITLE
[Feature Request] <Title of your feature>add responsiveness

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [Ajay-Dhangar/algo#538]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. Example: "I'm frustrated when..."

### Additional context

---

**Would you like to work on this feature?**  
- [ ] Yes  
- [ ] No

**Comment by ajay-dhangar** [comment]
Can you describe the problem that prompted your feature request? What would you like to happen? What alternatives have you considered?

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
It's. By mistake
