### ISSUE TITLE
Add Documentation for Programming Fundamentals

### ISSUE THREAD

**Issue by ajay-dhangar** [Ajay-Dhangar/algo#551]
## **Description**:
We are building a comprehensive set of documentation for **Programming Fundamentals**. This includes topics like **Language Syntax**, **Control Structures**, **Functions**, **Object-Oriented Programming (OOP) Basics**, and **Pseudo Code**. Each section should be documented in detail, with examples and key concepts clearly explained.

The following steps outline how contributors can set up the folder structure and write documentation for each of the topics listed below.

## **Project Structure**:
The structure will include a main folder named `fundamentals/`, with subfolders for each section. Here's an example of how the folder structure should look:

```
docs/
└── fundamentals/
    ├── language-syntax/
    │   ├── variables.md
    │   ├── operators.md
    │   ├── functions.md
    │   └── ... (other topics)
    ├── control-structures/
    │   ├── If-else.md
    │   ├── switch.md
    │   ├── for-loop.md
    │   └── ... (other topics)
    ├── functions/
    │   ├── function-declaration.md
    │   ├── function-call.md
    │   ├── function-parameters.md
    │   └── ... (other topics)
    ├── opp-basics/
    │   ├── classes.md
    │   ├── objects.md
    │   ├── inheritance.md
    │   └── ... (other topics)
    ├── pseudo-code/
    │   ├── introduction.md
    │   ├── variables.md
    │   ├── operators.md
    │   └── ... (other topics)
```

## **Steps to Contribute**:

1. **Create Folder Structure**:
   - Inside the `docs/` directory, create a folder named `fundamentals/`.
   - For each of the categories listed below, create a subfolder (e.g., `language-syntax/`, `control-structures/`, `functions/`, etc.).
   - Inside each subfolder, create markdown files (`.md`) for each topic in the section.

2. **Write Documentation**:
   - Each `.md` file should include a concise explanation of the topic, syntax (where applicable), examples, and key points.
   - Follow this template for each topic:
     ```
     ---
     id: ___ <!-- Unique identifier for the route. -->
     title: ___ <!-- Title of the topic. -->
     sidebar_label: ___ <!-- Topic label for the sidebar. -->
     sidebar_position: ___ <!-- Topic number for the sidebar. -->
     description: ___ <!--  A short SEO-friendly description. No HTML tags. -->
     tags: [___, __, ] <!-- Relevant tags for the problem. -->
     ---
     
     ## Overview
     A brief introduction to the topic.
     
     ## Syntax
     Provide the syntax or structure of the concept (if applicable).
     
     ## Example
     Demonstrate the concept with examples.
     
     ## Key Points
     - List any important notes or tips related to the topic.
     ```

3. **Categories & Topics**:

   - [ ] **Language Syntax**:
     - Topics: `Variables`, `Operators`, `Functions`, `Loops`, `Conditionals`, `Arrays`, `Strings`, `Classes`, `Objects`, `Inheritance`, `Polymorphism`, `Interfaces`
   
   - [ ] **Control Structures**:
     - Topics: `If-else`, `Switch`, `For Loop`, `While Loop`, `Do-While Loop`, `Break`, `Continue`, `Return`, `Try-Catch`, `Throw`, `Finally`
   
   - [ ] **Functions**:
     - Topics: `Function Declaration`, `Function Call`, `Function Parameters`, `Function Return`, `Function Scope`, `Function Overloading`, `Function Recursion`, `Function Closures`, `Function Currying`, `Function Composition`, `Function Memoization`
   
   - [ ] **OOP Basics**:
     - Topics: `Classes`, `Objects`, `Inheritance`, `Polymorphism`, `Encapsulation`, `Abstraction`, `Interfaces`, `Abstract Classes`, `Composition`, `Delegation`, `Mixins`
   
   - [ ] **Pseudo Code**:
     - Topics: `Introduction`, `Variables`, `Operators`, `Functions`, `Loops`, `Conditionals`, `Arrays`, `Strings`, `Classes`, `Objects`, `Inheritance`, `Polymorphism`

4. **Commit Your Changes**:
   - Once you have written documentation for a specific category or topic, commit your changes with a proper commit message.
   - Use the following format for commit messages:
     ```
     [Category] Add documentation for [Topic]
     Example: language-syntax Add documentation for variables
     ```

5. **Submit a Pull Request**:
   - After committing your changes, submit a pull request with the title: `Add [Category] Documentation`.
   - In the description, mention the specific topics you worked on.

## **Expected Outcome**:
By the end of this task, the project should have comprehensive, beginner-friendly documentation for the core programming fundamentals, covering language syntax, control structures, functions, and OOP principles.

## **Important Notes**:
- Keep the language simple and accessible, especially for beginners.
- If contributing to multiple sections, feel free to do so in separate pull requests.
  
## **Need Help?**:
If you have any questions or need guidance, feel free to comment on this issue or consult our [CONTRIBUTING.md](https://github.com/ajay-dhangar/algo/blob/main/CONTRIBUTING.md) guide.

Thank you for contributing to the project! Your efforts help improve the learning experience for everyone. 🚀

## 📧 Contact

Have questions or suggestions? Feel free to reach out by opening an issue or connecting via [GitHub Discussions](https://github.com/ajay-dhangar/algo/discussions).

**Comment by Ruksina01** [comment]
Hey @ajay-dhangar ,
I am interested in this issue, can you assign it to me?

**Comment by ajay-dhangar** [comment]
Hey @Ruksina01, thanks for your interest in this issue. You can work on any topic that interests you, but please focus on one topic at a time. Also, please mention which topic you'd like to work on, as selecting multiple topics may create complexity for both of us.

**Comment by Ruksina01** [comment]
Hey @ajay-dhangar 
I’m choosing to work on Language Syntax in C++, covering topics like Variables, Operators, Functions, Loops, Conditionals, Arrays, Strings, Classes, Objects, Inheritance, Polymorphism, and Interfaces. I’ll focus on one topic at a time.

**Comment by ajay-dhangar** [comment]
> Hey @ajay-dhangar I’m choosing to work on Language Syntax in C++, covering topics like Variables, Operators, Functions, Loops, Conditionals, Arrays, Strings, Classes, Objects, Inheritance, Polymorphism, and Interfaces. I’ll focus on one topic at a time.

Sure, @Ruksina01. You can go ahead and start working on this issue. Please let me know if you have any questions.

**Comment by ajay-dhangar** [comment]
> Hey @ajay-dhangar I’m choosing to work on Language Syntax in C++, covering topics like Variables, Operators, Functions, Loops, Conditionals, Arrays, Strings, Classes, Objects, Inheritance, Polymorphism, and Interfaces. I’ll focus on one topic at a time.

I think you need to work on the https://github.com/ajay-dhangar/algo/issues/550  issues because C++ language is on #550. This issue is based on fundamentals with all languages.

**Comment by devkartikrathi** [comment]
I am interested to contribute.

**Comment by ajay-dhangar** [comment]
> I am interested to contribute.

which topic

**Comment by devkartikrathi** [comment]
Documentation for fundamentals of programming, given it is not yet done. I am also interested in working on problems based on LLMs and NLP, Please suggest and share your views also.

**Comment by varshapandiann** [comment]
I would like to work on Programming Fundamentals of Java. Kindly assign me this issue @ajay-dhangar

**Comment by Ruksina01** [comment]
> > Hey @ajay-dhangar I’m choosing to work on Language Syntax in C++, covering topics like Variables, Operators, Functions, Loops, Conditionals, Arrays, Strings, Classes, Objects, Inheritance, Polymorphism, and Interfaces. I’ll focus on one topic at a time.
> 
> I think you need to work on the #550 issues because C++ language is on #550. This issue is based on fundamentals with all languages.

Yes, I can work with that issue in C++, can you assign that to me?

**Comment by Alpha1zln** [comment]
I would like to work on Programming Fundamentals. 
Categories- OOP Basics.
Kindly assign me this issue @ajay-dhangar 
I checked website and repository, I want to contribute to this website to help newbie programmers.

**Comment by ajay-dhangar** [comment]
> Documentation for fundamentals of programming, given it is not yet done. I am also interested in working on problems based on LLMs and NLP, Please suggest and share your views also.

sure you can work on this

**Comment by ajay-dhangar** [comment]
> I would like to work on Programming Fundamentals. Categories- OOP Basics. Kindly assign me this issue @ajay-dhangar I checked website and repository, I want to contribute to this website to help newbie programmers.

sure

**Comment by AvneetX25** [comment]
Hey ,
I would like to contribute on the topic Pseudo Code since it has not been taken by anyone . Can you please assign me this issue under gsoc-ext ?
