### ISSUE TITLE
Adding remaining quizzes

### ISSUE THREAD

**Issue by AswaniBolisetti** [Ajay-Dhangar/algo#553]
@ajay-dhangar 
There are only 2 quizzes available, for remaining topics quiz is not available, i would like to quiz for all the remaining
![quiz](https://github.com/user-attachments/assets/dda481cd-b01f-44c2-84fb-cc1bf75a4b26)

**Comment by ajay-dhangar** [comment]
@AswaniBolisetti, sure you can work on this but we need better UI/UX design with interactive.
