### ISSUE TITLE
Issue Title: "Add Scroll Progress Bar Feature"

### ISSUE THREAD

**Issue by AswaniBolisetti** [Ajay-Dhangar/algo#555]
@ajay-dhangar 
Issue Description: I would like to add a scroll progress bar to the website. This feature will display a progress bar at the top of the page, indicating how much the user has scrolled through the page. It enhances user experience by providing a visual cue for page navigation.

Please assign this issue to me under the labels: level2, gssoc-ext, and hacktoberfest-accepted.

**Comment by ajay-dhangar** [comment]
This feature may be good for some sites, but it doesn't fit our site. Please try another issue.
