### ISSUE TITLE
Adding few important algorithms

### ISSUE THREAD

**Issue by aditya07389** [Ajay-Dhangar/algo#568]
## @ajay-dhangar , I want to add some algorithms

1) Strand sort in sorting algorithms

2) Priority Scheduling ,multilevel queue scheduling and least recently used (LRU)

3) Tail recursion,Non tail recursion , tree recursion,mutual recursion

assign this to me under gssoc extd and hacktoberfest

**Comment by aditya07389** [comment]
hey @ajay-dhangar  can you please add a higher label ? I am adding 8 algorithms in total :)

**Comment by ajay-dhangar** [comment]
> hey @ajay-dhangar can you please add a higher label ? I am adding 8 algorithms in total :)

I'll reassign level based on your content because we need quality content, not quantity of content so, make sure focus on quality,

**Comment by aditya07389** [comment]
Okay cool, I'll raise pr by tomorrow
