### ISSUE TITLE
Add Red-Black Tree (RBT) to BST

### ISSUE THREAD

**Issue by jvkousthub** [Ajay-Dhangar/algo#577]
### Is your feature request related to a problem? Please describe.
There is no Red-Black Tree (RBT) in BST

### Describe the solution you'd like
Add Red-Black Tree (RBT) to BST 

### Additional context

---

**Would you like to work on this feature?**  
- [x] Yes  
- [ ] No

**Comment by jvkousthub** [comment]
@ajay-dhangar Assign me with this issue

**Comment by AnushkaChouhan25** [comment]
Please assign this issue to me with gsoc-exd and hacktoberfest label and suitable level label, I want to contribute in it. @ajay-dhangar
