### ISSUE TITLE
[General] Enhancing the icon and get involved today section

### ISSUE THREAD

**Issue by AE-Hertz** [Ajay-Dhangar/algo#584]
### Issue Description
the current icon of markdown and the get involved today section looks kindof off in dark mode, i will give a little tweak in changing their colors in dark mode, that will help in good user experience in dark mode.

### Additional Context
![Screenshot 2024-10-12 184409](https://github.com/user-attachments/assets/34d21abf-8188-49b1-b58a-1f4b437988af)
![Screenshot 2024-10-12 184420](https://github.com/user-attachments/assets/f9f3e764-ec9f-4a8c-8dba-bb2305f45256)

---

**Would you like to work on this issue?**  
   Yes

**Comment by AE-Hertz** [comment]
please make this under gssoc 24 and hacktoberfest-accepted

**Comment by keikurono7** [comment]
I'd like to work on this

**Comment by keikurono7** [comment]
working on it

**Comment by ajay-dhangar** [comment]
> /assignme

@keikurono7, you need to work on another issue because @AE-Hertz is already assigned. We work on a first-come, first-served basis.
