### ISSUE TITLE
[Bug] Footer Links Broken

### ISSUE THREAD

**Issue by rahuldave2005** [Ajay-Dhangar/algo#61]
### Describe the bug
Links are not present for the Discord and Contributors In Footer of the Website

### To Reproduce
1. You can check the footer , Discord and Contributor Button is not redirecting to any other page

### Expected behavior
Must be Redirected to Discord Server and The Contributor page of github

### Screenshots
![image](https://github.com/user-attachments/assets/8c36b02b-1dea-4f98-91d8-a72cfc69dc21)

Here Changes Need to be Done in Code :
![image](https://github.com/user-attachments/assets/80a99b1f-d82d-4031-9192-fe362a842ad8)

### Additional context
Please Assign This issue to me under Gssoc-extd and HacktoberFest . Thanks !

**Would you like to work on this issue?**  
Yes

**Comment by BaunaBadmosh** [comment]
yeah its a valid bug. can you validate #60

**Comment by rahuldave2005** [comment]
> yeah its a valid bug. can you validate #60

yes it is valid and it needs to be solved !!
