### ISSUE TITLE
Pagination "Next" Button Styling Issue

### ISSUE THREAD

**Issue by TornovDutta** [Ajay-Dhangar/algo#618]
# Issue:
The "Next" button in the pagination appears poorly designed, with inconsistent alignment and spacing between the text and the adjacent link ("Trie"). The button lacks proper visual appeal, contrast, and interactive cues, making it feel disconnected from the rest of the interface. This affects the user experience and clarity.

# Expected Solution:
Improve the styling by adding better padding, consistent font size, and a more engaging design (e.g., hover effects) to ensure the button is visually appealing and user-friendly.

### sceenshot:
![Screenshot 2024-10-13 114947](https://github.com/user-attachments/assets/d312c2a6-2279-43d6-9ff9-88085b9760fd)

**Comment by TornovDutta** [comment]
@ajay-dhangar please label and assign the issuse

**Comment by TornovDutta** [comment]
> 👋 Hi @TornovDutta! Thank you for opening your first issue on the Algo project. We're excited to help you out and appreciate your contribution. Please provide as much detail as possible to assist us in addressing the issue effectively. Welcome aboard! 😊

Hi! 😊 Thank you for the warm welcome! I’ve provided as many details as possible in the issue description. Let me know if you need further clarification or additional information. Looking forward to working together on this!

**Comment by ajay-dhangar** [comment]
Thank you for your suggestion, @TornovDutta. We think the current pagination "Next" button is good and meets our requirements. However, if you would like to work on improving it, please provide us with a demo and full details. Otherwise, we will close this issue.

**Comment by TornovDutta** [comment]
> Thank you for your suggestion, @TornovDutta. We think the current pagination "Next" button is good and meets our requirements. However, if you would like to work on improving it, please provide us with a demo and full details. Otherwise, we will close this issue.

Thank you for your response. Could I take today to work on the demo? Please don't close the issue just yet.
@ajay-dhangar
