### ISSUE TITLE
[Bug] Blog page is not working

### ISSUE THREAD

**Issue by praveenarjun** [Ajay-Dhangar/algo#63]
### Describe the bug
The blog page is not working as expected. It does not load any content and displays a blank page.

### To Reproduce
steps to reproduce the behavior:

   1. Go to the homepage of the application.
    2.Navigate to the 'Blog' section using the top navigation bar.
   3. Observe that the blog page remains blank without any content.

### Expected behavior
User can write there comments and blogs 

### Screenshots
![Screenshot 2024-10-05 at 1 04 58 AM](https://github.com/user-attachments/assets/cdec47bc-4959-4e35-a0ee-686718af31cc)
On clicking the name it redirecting the home page
![Screenshot 2024-10-05 at 1 11 42 AM](https://github.com/user-attachments/assets/637b07de-c13a-49fc-86ff-0d9277de738b)

lock it is giving front page 

### Additional context

**Would you like to work on this issue?**  
- [ ] Yes

**Comment by praveenarjun** [comment]
pls add labels so that it will be helpful

**Comment by ajay-dhangar** [comment]
You can write blog content. For author information, I need to set up the blog. Today, I set up the view for all authors' profiles, including their social links.

**Comment by praveenarjun** [comment]
Can you give me labels

**Comment by ajay-dhangar** [comment]
> You can write blog content. For author information, I need to set up the blog. Today, I set up the view for all authors' profiles, including their social links.

- https://codeharborhub.github.io/blog/authors/ajay-dhangar/
- https://codeharborhub.github.io/blog/authors
