### ISSUE TITLE
[Feature Request] Adding a clear blog page so that user can add there comments and requests 

### ISSUE THREAD

**Issue by praveenarjun** [Ajay-Dhangar/algo#64]
### Describe the solution you'd like
Implement a functional blog page that allows users to add their comments and requests. This page should:

    Display recent blog posts and comments.
    Provide a form for users to submit new comments and requests.
    Include navigation links to other parts of the application.

### Describe alternatives you've considered

    Integrating a third-party blog platform.
    Using a static page with a simple feedback form.

### Additional context
![Screenshot 2024-10-05 at 1 04 58 AM](https://github.com/user-attachments/assets/8e1130cb-a11a-4b01-b5bc-28150cd01847)

---

**Would you like to work on this feature?**  
-  Yes

**Comment by praveenarjun** [comment]
add labels so that it will be helpfull

**Comment by ajay-dhangar** [comment]
checkout https://ajay-dhangar.github.io/algo/docs/#get-started-with-algo
