### ISSUE TITLE
[Feature Request] Add easy strings leetcode solutions

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [Ajay-Dhangar/algo#652]
### Is your feature request related to a problem? Please describe.
Add easy strings leetcode solutions
### Describe the solution you'd like
Add easy strings leetcode solutions
### Describe alternatives you've considered
Add easy strings leetcode solutions
### Additional context

---

**Would you like to work on this feature?**  
- [x] Yes  
- [ ] No

**Comment by ajay-dhangar** [comment]
Please don't create spam. We need only four issues open, not a large number. If you want to work on more issues, you can try other open source projects. A large number of issues in a single project can create problems for you and for us.
