### ISSUE TITLE
adding scroll progress bar

### ISSUE THREAD

**Issue by AswaniBolisetti** [Ajay-Dhangar/algo#656]
@ajay-dhangar 
i would like to add a scroll progress bar
could you please assign me this issue

**Comment by ajay-dhangar** [comment]
Can you share with us a demo of the scroll progress bar? We'd like to see it in action.

**Comment by AswaniBolisetti** [comment]
@ajay-dhangar 

https://github.com/user-attachments/assets/34778108-40ac-4cb7-8238-ee3f7f60e762

**Comment by ajay-dhangar** [comment]
Thank you for your suggestion, @AswaniBolisetti. While your idea is good, it doesn't fit our site. Unfortunately, we can't use your idea.
