### ISSUE TITLE
[Feature Request] Adding All the Basic Algorithms implemented in Trees 

### ISSUE THREAD

**Issue by karanmaheshwari16** [Ajay-Dhangar/algo#663]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the different algorithms of trees are for easy one stop understanding

### Describe the solution you'd like
A clear and concise code structure for all the algo's required 

---

**Would you like to work on this feature?**  
- [x] Yes  
- [ ] No

**Comment by karanmaheshwari16** [comment]
hi @ajay-dhangar i am new to open source and i just can't find a way to add labels for hactober fest and girlscript can you please accept my issue and help me with the labels

**Comment by ajay-dhangar** [comment]
> hactober fest

Our repo is DSA-based, so it can't be counted in Hacktoberfest. However, it can be counted in GirlScript with points.
