### ISSUE TITLE
UPDATION IN README.md FILE REQUIRED

### ISSUE THREAD

**Issue by soham0028** [Ajay-Dhangar/algo#680]
Hello @ajay-dhangar 
the current readme file lacks proper structure and does not contain alot of things such as:

1. Featured in section 
2. Table of contents for easy access
3. back to top button 
4. contributors , forkers & stargazers section 

Kindly Assign me the issue under gsssoc-extd and hacktoberfest labels so my work counts under these events .
Thankyou

**Comment by ajay-dhangar** [comment]
@soham0028, can you also, add

```md
## Resources for Guidance
Here are some resources that may be helpful as you contribute to Algo:
- [Docusaurus Documentation](https://docusaurus.io/docs/docs-introduction)
- [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)
```

because it is very important for our contributors

**Comment by soham0028** [comment]
okay done 
will revert back asap
