### ISSUE TITLE
[Feature Request] Adding a Contribution Guide Video for newbies

### ISSUE THREAD

**Issue by J-B-Mugundh** [Ajay-Dhangar/algo#692]
### Is your feature request related to a problem? Please describe.
Several individuals have reached out on LinkedIn seeking guidance on contributing to the repository. Currently, there isn’t a visual guide that walks new contributors through the process. A contribution video could significantly help new contributors, especially those unfamiliar with open-source practices.

### Describe the solution you'd like
A short, clear, and comprehensive video tutorial that explains how to contribute to the repository. The video should cover:

- Cloning the repository
- Creating a new branch
- Making changes or adding features to the docs folder
- Running it in local to verify the changes
- Committing changes and pushing to GitHub
- Opening a pull request

### Additional context

---

**Would you like to work on this feature?**  
- [x] Yes  
- [ ] No

**Comment by ajay-dhangar** [comment]
Sure, @J-B-Mugundh, you can make the contribution guide video. We can reference it in our contributing guidelines.
