### ISSUE TITLE
[Feature Request] Update challenge 2  questions as challenge 2 and challenege 1 showing same questions and options

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [Ajay-Dhangar/algo#724]
### Is your feature request related to a problem? Please describe.
challenge 2 and challenege 1 showing same questions and options
### Describe the solution you'd like
challenge 2 and challenege 1 showing same questions and options
### Describe alternatives you've considered
challenge 2 and challenege 1 showing same questions and options
### Additional context

---

**Would you like to work on this feature?**  
- [x] Yes  
- [ ] No

**Comment by ajay-dhangar** [comment]
Please don't create spam. We need only four issues open, not a large number. If you want to work on more issues, you can try other open source projects. A large number of issues in a single project can create problems for you and for us.
