### ISSUE TITLE
[Feature Request] <Title of your feature>add solutions to quiz on queues

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [Ajay-Dhangar/algo#736]
### Is your feature request related to a problem? Please describe.
add solutions to quiz on queues
### Describe the solution you'd like
add solutions to quiz on queues
### Describe alternatives you've considered
add solutions to quiz on queues
### Additional context

---

**Would you like to work on this feature?**  
- [x] Yes  
- [ ] No

**Comment by ajay-dhangar** [comment]
Please don't create spam. We need only four issues open, not a large number. If you want to work on more issues, you can try other open source projects. A large number of issues in a single project can create problems for you and for us.
