### ISSUE TITLE
[Bug] <Title of your bug>Queues solution leading to the Queue quiz page

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [Ajay-Dhangar/algo#766]
### Describe the bug
Queues solution leading to the Queue quiz page.
<img width="958" alt="queue" src="https://github.com/user-attachments/assets/45441ddb-6ade-4f67-8697-fbd611c37800">

### To Reproduce
2. Click on '...'
3. Scroll down to '...'

### Additional context

---

**Would you like to work on this issue?**  
- [x] Yes  
- [ ] No

**Comment by ajay-dhangar** [comment]
Please don't create spam. We need only four issues open, not a large number. If you want to work on more issues, you can try other open source projects. A large number of issues in a single project can create problems for you and for us.
