### ISSUE TITLE
Important❗❗ This repository has been excluded from Hacktoberfest

### ISSUE THREAD

**Issue by akash70629** [Ajay-Dhangar/algo#789]
### Issue Description

@ajay-dhangar What's going on ?!!! 😰😰

**Website** - [hacktoberfest.com](hacktoberfest.com)

### Additional Context
![image](https://github.com/user-attachments/assets/31ec90e4-8db3-4790-b429-7e92bba28385)
![image](https://github.com/user-attachments/assets/3634ea9c-d990-4a46-aaeb-18c42ecf95b1)

**Comment by akash70629** [comment]
@ajay-dhangar please reply

**Comment by ajay-dhangar** [comment]
@akash70629, because Algo is based on dsa and also, docs based, it might be breaking roles.
