### ISSUE TITLE
Misalignment of "Resources" and "Community" Headings in Footer Section

### ISSUE THREAD

**Issue by ansiace** [Ajay-Dhangar/algo#849]
In the footer section, the "Resources" and "Community" headings are not properly aligned, causing an inconsistency in the layout. This impacts the overall visual balance and user interface. To improve UI performance and design consistency, these headings should be aligned properly.

### Current Behavior
- The "Resources" and "Community" headings in the footer are misaligned, resulting in an unbalanced appearance.

### Expected Behavior
- The "Resources" and "Community" headings should be properly aligned, maintaining uniform spacing and alignment within the footer section.

![image](https://github.com/user-attachments/assets/607b7e73-cb6e-40b6-8ded-4606653aba6e)

**Comment by ajay-dhangar** [comment]
I think this issue is caused by one of the .css files. @ansiace, you can check out every .css file to find the culprit.

**Comment by ansiace** [comment]
"Thank you for the suggestion! I'd be happy to investigate the issue by checking the relevant .css files to identify the cause. Could you please assign this issue to me so I can start working on it?"

**Comment by ansiace** [comment]
Please assign it i'll sure solve this issue.
