### ISSUE TITLE
[Feature Request] Basic Operations on Binary Trees

### ISSUE THREAD

**Issue by KhawajaFashi** [Ajay-Dhangar/algo#85]
### Is your feature request related to a problem? Please describe.
Binary trees are widely used in various applications, and understanding their basic operations is crucial for effectively implementing and utilizing this data structure. 

### Describe the solution you'd like
I propose adding a section that covers basic operations on binary tree.
1. Insertion
2. Deletion
3. Searching
4. Traversal

### Describe alternatives you've considered

**Linked Lists:**

- Although useful for sequential data, they lack the hierarchical structure that binary trees provide.

**Hash Tables:**

- While fast for lookups, they do not maintain order and can be inefficient for applications that require sorted data.

**Graphs:**

- Though capable of representing complex relationships, they introduce unnecessary complexity for scenarios best suited for binary trees.

---

**Would you like to work on this feature?**  
- [X] Yes  
- [ ] No

**Comment by ishita-babar** [comment]
can you assign this to me, also can you update the label to include hacktober

**Comment by ajay-dhangar** [comment]
> can you assign this to me, also can you update the label to include hacktober

@ishita-babar, I see that @KhawajaFashi already claimed this issue. Would you like to work on another issue instead?

**Comment by ishita-babar** [comment]
okay
