### ISSUE TITLE
[Feature Request] <N-ary tree>

### ISSUE THREAD

**Issue by priyashuu** [Ajay-Dhangar/algo#874]
## 🚀 Feature Request

N-ary Tree
Problem: Documentation does not cover traversal methods effectively.
Solution: Include examples of traversal methods (preorder, postorder) for N-ary Trees.
Alternatives: Users can reference generic tree traversal tutorials, leading to confusion.
Additional Context: Specific examples will improve comprehension and usage.

**Would you like to work on this feature?**  
- [x] Yes  
- [ ] No

**Comment by ajay-dhangar** [comment]
Don't create spams we need only open 4 issue / contributor
