### ISSUE TITLE
[Feature Request] Linked Lists

### ISSUE THREAD

**Issue by KhawajaFashi** [Ajay-Dhangar/algo#91]
### Is your feature request related to a problem? Please describe.
I often find myself needing to manage collections of data that can grow and shrink dynamically. Linked lists are a fundamental data structure that allows for efficient insertion and deletion of elements. Unlike arrays, linked lists do not require contiguous memory allocation, making them more suitable for dynamic datasets that frequently change in size. Linked Lists can help manage big collection of data very easily.

### Describe the solution you'd like
I would like to implement a linked list data structure that supports the following operations:

- Insertion: Add elements at the head, tail, or at a specific position in the list.
- Deletion: Remove elements by value or position, allowing for easy management of the dataset.
- Traversal: Traverse the linked list to display its contents, facilitating better visualization of the data.
- Searching: Implement a search function to find specific elements within the list.

### Describe alternatives you've considered
I considered using arrays or dynamic arrays; however, they do not provide efficient insertion and deletion capabilities, especially when dealing with large datasets or frequent updates.

### Additional context
Implementing linked lists will help us tackle various problems more efficiently, such as managing user inputs, processing queues, or implementing stacks.

---

**Would you like to work on this feature?**  
- [X] Yes  
- [ ] No

**Comment by AnujSaha0111** [comment]
I want to work on it. Can you please assign it to me?

**Comment by AnujSaha0111** [comment]
Solved it in https://github.com/ajay-dhangar/algo/pull/131
