### ISSUE TITLE
[General] Add Solution for Detecting a Loop in a Linked List

### ISSUE THREAD

**Issue by riyaa060** [Ajay-Dhangar/algo#916]
### Issue Description
This issue proposes adding a solution to detect a loop in a linked list using Floyd's Cycle-Finding Algorithm (Tortoise and Hare algorithm). This is a common problem in data structures, and providing a clear, efficient implementation would be beneficial for users.

---

**Would you like to work on this issue?**  
- [x] Yes  
- [ ] No

**Comment by nishant4500** [comment]
#570  i have already done it can you change it my label to level 2

**Comment by riyaa060** [comment]
Could you please assign this to me  @ajay-dhangar
