### ISSUE TITLE
 Add program to delete middle node of a linked list (DSA)

### ISSUE THREAD

**Issue by riyaa060** [Ajay-Dhangar/algo#933]
### Issue Description
I would like to propose adding a solution to delete the middle node from a singly linked list. This functionality is useful for various linked list manipulations and can improve the overall capabilities of our data structure implementations.

#### Suggested Implementation
I suggest implementing the solution in the following languages (choose the relevant ones):
- Python
- Java
- C++
---

**Would you like to work on this issue?**  
- [x] Yes  
- [ ] No

**Comment by dev628140** [comment]
Hi, I would like to work on this issue. Please assign this to me

**Comment by ajay-dhangar** [comment]
> Hi, I would like to work on this issue. Please assign this to me

@dev628140 create new issues
