### ISSUE TITLE
[Feature Request] Random Forest Algorithm in ML

### ISSUE THREAD

**Issue by kartik1112** [Ajay-Dhangar/algo#958]
### Is your feature request related to a problem? Please describe.
Currently, decision tree-based models often suffer from overfitting or lack robustness in certain datasets. Using a single decision tree can be unreliable for high-dimensional or noisy data. A Random Forest algorithm would help mitigate these issues by aggregating multiple decision trees, leading to better predictive performance.

### Describe the solution you'd like
Implement a **Random Forest Algorithm**, which constructs a collection of decision trees (a forest) during training and outputs the mode of classes for classification or the average prediction for regression. This ensemble approach would improve model accuracy, reduce overfitting, and handle both categorical and continuous features more efficiently.

### Describe alternatives you've considered
I have considered boosting techniques or bagging individual decision trees. However, a Random Forest is preferable for handling noise and complex datasets without requiring excessive tuning.

### Additional context
Adding this feature would enhance the model's scalability and flexibility, making it suitable for a wide range of real-world applications, including classification and regression tasks in various domains like finance, healthcare, and e-commerce.

---

**Would you like to work on this feature?**  
- [x] Yes  
- [ ] No

**Comment by dev628140** [comment]
Hi, I would like to work on this issue. Please assign this to me

**Comment by kartik1112** [comment]
Thanks @dev628140 but I've already raised a PR

**Comment by kartik1112** [comment]
@ajay-dhangar already opened a PR for this issue please review
