### ISSUE TITLE
[Feature]: Gradient Boosting Algo

### ISSUE THREAD

**Issue by inkerton** [Ajay-Dhangar/algo#971]
### Feature Name

Gradient Boosting Algorithm

### Feature Description

Gradient Boosting is a machine learning algorithm that iteratively trains weak models (often decision trees) and combines them to create a strong predictive model. It works by fitting a new model to the residuals of the previous models, focusing on the areas where the current model is making mistakes. This iterative process helps to improve the overall accuracy and performance of the model.

### Motivation

Gradient Boosting is often known for its ability to achieve high accuracy, especially on complex datasets. By combining multiple weak models, it can capture intricate patterns and relationships that might be missed by a single model.

### Feature Type

New Algorithm

### Does this feature require additional resources?

- [ ] Additional Documentation
- [ ] Third-Party Libraries
- [ ] UI/UX Design
- [ ] Other

**Comment by ajay-dhangar** [comment]
open document issues for docs
