### ISSUE TITLE
[Feature]: Principal Component Analysis (PCA)

### ISSUE THREAD

**Issue by inkerton** [Ajay-Dhangar/algo#972]
### Feature Name

Principal Component Analysis (PCA) Algorithm

### Feature Description

Principal Component Analysis (PCA) is a dimensionality reduction technique that transforms a high-dimensional dataset into a new coordinate system with uncorrelated features. It identifies the principal components, which are linear combinations of the original features that capture the most variance in the data. By projecting the data onto these principal components, you can reduce the dimensionality while preserving the most important information.   

### Motivation

PCA can significantly reduce the number of features in your dataset, which can lead to faster training times, improved model performance, and reduced computational costs.

### Feature Type

New Algorithm

### Does this feature require additional resources?

- [ ] Additional Documentation
- [ ] Third-Party Libraries
- [ ] UI/UX Design
- [ ] Other

**Comment by ajay-dhangar** [comment]
open document issues for docs
