### ISSUE TITLE
[Feature]: Singular Value Decomposition (SVD)

### ISSUE THREAD

**Issue by inkerton** [Ajay-Dhangar/algo#973]
### Feature Name

Singular Value Decomposition (SVD)

### Feature Description

Singular Value Decomposition (SVD) is a matrix factorization technique that decomposes a matrix into the product of three matrices:   

U: An orthogonal matrix containing the left singular vectors.
Σ: A diagonal matrix containing the singular values.
V: An orthogonal matrix containing the right singular vectors.
SVD is a powerful tool for analyzing and manipulating matrices, with applications in various fields, including machine learning, data science, and image processing.

### Motivation

SVD provides a fundamental way to factorize matrices, which can be useful for tasks like dimensionality reduction, denoising, and recommendation systems.

### Feature Type

New Algorithm

### Does this feature require additional resources?

- [ ] Additional Documentation
- [ ] Third-Party Libraries
- [ ] UI/UX Design
- [ ] Other

**Comment by ajay-dhangar** [comment]
open document issues for docs
