### ISSUE TITLE
[Feature]: Add Kadane's Algorithm to the Algorithm Blog Section

### ISSUE THREAD

**Issue by Lokesh-Bijarniya** [Ajay-Dhangar/algo#975]
### Feature Name

Kadane's Algorithm (Maximum Subarray Problem)

### Feature Description

Kadane's Algorithm is an efficient solution to the maximum subarray problem, which involves finding the contiguous subarray within a one-dimensional numeric array that has the largest sum. The algorithm uses dynamic programming to solve this in linear time, making it optimal for large datasets.

Kadane's Algorithm is a widely studied algorithm in competitive programming and interviews, due to its simplicity and efficiency. Adding a detailed blog about Kadane's Algorithm will help readers understand how to approach dynamic programming problems and improve their coding skills.

The blog would explain:

- What the maximum subarray problem is.
- The thought process behind Kadane's Algorithm.
- A step-by-step breakdown of the algorithm.
- The final optimized code in multiple languages (e.g., Java, Python).
- Potential real-life applications of the algorithm.

### Motivation

Kadane’s Algorithm is a foundational algorithm that is used in various real-world applications, such as financial analysis (to find the best time to buy/sell stocks) or network routing problems. It’s highly useful for students preparing for coding interviews and contests, as well as developers looking to optimize their array-handling code.

Adding this algorithm to the blog section will provide:

- A learning resource for beginners and advanced programmers.
- Detailed explanations and code snippets that help users understand dynamic programming.
- A deeper understanding of efficient problem-solving techniques.
- It will enhance the value of the algorithm blog by adding one of the most famous algorithms, which is frequently asked in coding interviews and challenges.

### Implementation Suggestions (Optional)

The blog post could be structured with the following sections:

- Introduction to the maximum subarray problem.
- Explanation of a brute-force solution and its limitations.
- Transition to Kadane's Algorithm with a clear explanation of the dynamic programming approach.
- Code implementation of Kadane’s Algorithm in Java, Python, and C++.
- Performance analysis (Time complexity: O(n), Space complexity: O(1)).
- Conclusion with real-world applications and additional resources for further learning.

### Feature Type

New Algorithm

### Does this feature require additional resources?

- [X] Additional Documentation
- [ ] Third-Party Libraries
- [ ] UI/UX Design
- [ ] Other

### References (Optional)

Kadane’s Algorithm - GeeksforGeeks

**Comment by Lokesh-Bijarniya** [comment]
@ajay-dhangar could u assign me ?

**Comment by ajay-dhangar** [comment]
@Lokesh-Bijarniya can you close feature issues and open document issues for docs
