### ISSUE TITLE
[Feature]: New concept in Javascript "Closures in javascript"

### ISSUE THREAD

**Issue by AmanPathan** [Ajay-Dhangar/algo#976]
### Feature Name

Add new concept in javascript

### Feature Description

Adding closures concept in javascript section. It contains detailed explanation of clousres in javascript.

### Motivation

It provides users information about one of the important concept in javascript that is "Closures".

### Feature Type

Documentation Enhancement

### Does this feature require additional resources?

- [ ] Additional Documentation
- [ ] Third-Party Libraries
- [ ] UI/UX Design
- [ ] Other

**Comment by ajay-dhangar** [comment]
@AmanPathan can you close feature issue and open document issues
