### ISSUE TITLE
[Feature]: Add Copy button In Interview Questions Solution

### ISSUE THREAD

**Issue by Uvesh99** [Ajay-Dhangar/algo#999]
### Feature Name

Add Copy button In Interview Questions

### Feature Description

Add Copy button In Interview Questions to copy code .

### Motivation

User can copy code directly and use it.

### Feature Type

Performance Optimization

### Does this feature require additional resources?

- [ ] Additional Documentation
- [ ] Third-Party Libraries
- [ ] UI/UX Design
- [X] Other

**Comment by ajay-dhangar** [comment]
No need
